### PR TITLE
Update todo capture pattern

### PR DESCRIPTION
**Pull request by samundra**
- Take commits from Rylon feature branch
- update todo capture pattern

### CODE REVIEW

**Comment by jonathandelgado** [comment]
Hey @samundra, unfortunately I cannot merge this. The two commits you plucked for mouse support were actually previously in this project and resulted in issue #49. When it comes to mouse support, I would love to add it, but I seriously doubt we will be able to implement it with sublime's current API, we have tried a lot of things.

As per your todo pattern change, it would break on languages that use `#` to denote a comment. I chose to keep it language agnostic for a reason.

**Comment by samundra** [comment]
@jonathandelgado :+1: Yeah got it. I also followed the discussion. However, we can at least have the *Regex* for maximum possibilities listed somewhere e.g. for `PHP, C++` etc.

**Comment by jonathandelgado** [comment]
@samundra What do you mean about the regex for maximum possibilities? There are thousands of programming languages, with a lot of possible comments, for example `//` in Javascript, `#` in python, even `'` in Visual Basic. The reason I made those regex matches agnostic is because I didn't want to leave any language out unknowingly.

**Comment by samundra** [comment]
@jonathandelgado I agree with you. It's nearly impossible to capture every possible programming languages out there. My thought was to have these patterns documented somewhere in Readme, Wiki etc. 

Maybe I was not clear enough at first time. I just mentioned *somewhere* but didn't emphasize it thus confusion was created. And if anyone really wants to use it, we always have options to customize the patterns in *User Settings*. It will take time to find right patterns for someone who is not familiar with regex. In those cases, they can just copy and paste those pre-defined patterns to their settings and get going. My final objective was this copy and paste ready patterns be documented somewhere in the repository. As community find it helpful, they will start contributing their pattern.

Lets assume someone, who has just got started in programming comes across this awesome **SublimeTodoReview** Plugin. Excited about the plugin, installs it just to find that it doesn't work as wished it to. Then realizes that right regex pattern is required for the plugin to know the tags but knows very little about the regular expressions.

I hope it wasn't confusing like the first time. :cold_sweat:

**Pull request closed without merging**
