### PR TITLE
Update TodoReview.py

### PR DESCRIPTION
**Pull request by zcold**
add filepaths arg for checking only some files

### CODE REVIEW

**Comment by jonathandelgado** [comment]
I might be missing something, but how is this different than the current `paths` argument? https://github.com/jonathandelgado/SublimeTodoReview#arguments

**Comment by zcold** [comment]
In the current version paths is dirpaths in Engine.
And according to TodoReviewCommand.run, we can 

1. check current file,
2. check current opened files,
3. check files in project (window.folders())
4. check files in the FOLDERS in settings.include_paths

However, I need to check some specific files only. My project has many random named huge logs/reports so I want only check some config files and source files. The easiest way is to update my in-house sublime package to filter files before run_command('todo_review').

**Comment by jonathandelgado** [comment]
Yeah, this is what the `args.path` option is for. https://github.com/jonathandelgado/SublimeTodoReview/blob/master/TodoReview.py#L151

This is the same argument that we use when you right click something on the tree to only search a specific file/folder, this should do what you want.

**Comment by zcold** [comment]
thanks

**Comment by zcold** [comment]
I have tested and if I provide file paths (not dir path) to paths, TodoReview will fail since loop boday in os.walk(<a file path not dir path>) will never be reached.

**Pull request closed without merging**
