### PR TITLE
test if files exist before adding to list of files

### PR DESCRIPTION
**Pull request by drevicko**
This is a resolution to problems discussed in #155 and #107.

As far as I can tell, the only way a broken symlink can get into the list of files is [here](https://github.com/jonathandelgado/SublimeTodoReview/blob/master/TodoReview.py#L173), where files in the command argument `paths` or in the view setting `include_paths` are added to the list.

The current test only checks `os.path.isfile()`, which [returns `True` for broken symlinks](https://docs.python.org/3.5/library/os.path.html#os.path.isfile). I've added a test for `os.path.exists()`, which will return [`False` for broken symlinks](https://docs.python.org/3.5/library/os.path.html#os.path.exists) in python 3 and [python 2](https://docs.python.org/2.7/library/os.path.html#os.path.exists).

### CODE REVIEW

**Comment by jonathandelgado** [comment]
I don't think this one is necessary. From what I understand, we were more worried about the stuff throwing an error during the `resolve` phase. Currently, we catch any IO errors at https://github.com/jonathandelgado/SublimeTodoReview/blob/master/TodoReview.py#L105 -- that should be good enough combined with the current `os.path.isfile` check.

Additionally, I think adding that check would add an additional IO hit for every file checked, which would drastically slow down scan times on large projects.

Please let me know if I am incorrect, I'm not a python-pro by any means.

**Comment by drevicko** [comment]
Currently, when 'resolve_symlinks' is set, any TODO's in open files with symlinks in their paths will be opened in a new tab when you select a TODO. If 'resolve_symlinks' is'nt set, the plugin crashes with broken symlinks. Neither of these behaviours are ideal. Checking that each file exists should fix the second case.

I think we should never resolve the symlinks in paths from open files, as that is what causes new tabs to be opened when we should be switching to the open tab. Imho, we shouldn't be resolving symlinks at all - it just doesn't seem a common use case. If we don't resolve symlinks, this PR should fix the broken simlink crash problem. 

Regards the overhead of an extra os call, I really don't think it's very high, especially if we also remove the `os.path.realpath` call. Btw, the `os.path.expanduser` call in `resolve()` (line 117) seems redundant - the `abspath` call should already do that, no? (at least on OS's I use it does).

What was the problem with broken symlinks when `os.path.realpath` wasn't used? Why wasn't that problem caught by the IOError try/catch? The only os call outside the try/catch I see is `os.path.walk()` on line [58](https://github.com/jonathandelgado/SublimeTodoReview/blob/master/TodoReview.py#L58), but `walk()` doesn't seem to be bothered by broken symlinks??

**Comment by drevicko** [comment]
I've been trying to replicate a crash with a broken symlink - didn't manage to find a way to make it happen. Perhaps it was fixed by later commits?

**Comment by jonathandelgado** [comment]
I was able to reproduce the crash on Windows, but that might just be a Windows specific issues, symlinks and unix-y things in general are oddly implemented. I haven't tested on another OS. To be honest, I haven't tried with this PR yet, it's on my list.

For the overhead remarks, I think your remark might be fair, I assumed `os.path.realpath` didn't hit disk, but that is most likely incorrect now that I'm thinking about it.

The one thing I am most sure about is that `os.path.expanduser` is required in addition to `os.path.abspath` - that might be a Windows oddity as well, but I remember hitting my head against the wall trying to get directories like `~/home` to work since it was a commonly requested feature.

To be honest, I'm not sure what is causing it and I don't have a ton of time to dive in and figure it out.

I guess the largest question I have for you is why this solution rather than the one previously implemented with the configuration? I think preventing the error from occurring by default, not breaking developers environments and keeping the resolve behavior the same is the most optimal solution. Adding that extra flag allows users that have a more advanced use-case to resolve those symlinks, but they also take on the risk of errors with OS-specific issues. It seems like a fair trade-off to me?

**Comment by drevicko** [comment]
Was there a traceback indicating what command broke? I'm afraid I don't have a windows machine to play with, just a mac, and I'd presume linux would behave similarly on file system related things. 

I'm not comfortable with the config solution to this as it's only a partial fix and the (current) default behaviour has already open files opening in new tabs (any file that has a simlink in it's path, not just rmate files). In most cases that's annoying and confusing, but probably doesn't result in lost data, so I can see that preventing a crash in some situations and allowing config for treating simlinks can be a good option. I can also see the argument for keeping the resolve behaviour the same.

The issue with new tabs for already open files is annoying and unexpected and in my case can result in loss of data until you understand a workaround, but is fixed with choosing not to resolve symlinks, though still clearly a bug.

Do you think the resolving symlink behaviour is something some users rely on? 

Interesting about abspath and expanduser - I'll stash that away for future reference! (:

**Comment by jonathandelgado** [comment]
I think you make a fair point, but I don't think that many people are dealing with symlinks and those who are now have the new flag to fix it. I just don't think overall it's worth the time I would throw into it trying to prevent windows crashes if I were to make that flag the new default.

I think what I can do is create a new issue, leave it in a backlog and do a major version bump when it is finally implemented, does that sound realistic to you?

**Comment by drevicko** [comment]
I guess so. For me, I can set the config and it'll do what I need. If there's someone out there with both problems, they'll have to just choose the lesser evil, but I guess it's likely an uncommon use case. I suspect this PR will fix the crash problem though. 

Here's a quick timing experiment on a headless linux server:
 - %timeit os.path.exists('f00o')
 - 4.42 µs ± 34.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

 and my mac
 - %timeit os.path.exists('foo')
 - 100000 loops, best of 3: 3.94 µs per loop
(similar times for existing files and broken symlinks)

You'd need to be scanning a million files to add ~5s execution time. Maybe Windows fs calls are much slower?

**Comment by jonathandelgado** [comment]
Hey, I just got around to testing this out. The PR actually ended up erroring out for me, I suspect you meant to use `os.path.exists(p)` instead of the `filepath` variable. I did some speed tests and on Windows and an HDD (I assume you tested on an SSD), it actually ended up adding almost 30s on a project with ~1k files.

I think end-all be-all on this, we need to just keep it the way it is. I'm glad we were able to add the configuration option so your use-case was addressed, but I can't in good will add such a performance hit to existing users (that are most likely happy with their symlink resolution) just for the small subset that need changes, they will have to edit the config.

**Comment by drevicko** [comment]
Thanks for making the test, and yes, if it's slowing it down that much, best to not do it - I suspect it's more a Windows vs. linux thing than due to an SSD HD, certainly the server I tested on doesn't have an ssd disk, even if my mac does (and they took about the same time). Apologies for lazily not testing before putting this up, and yes, it should have been `p`.
It's a shame we can't have the best of both worlds, but to do so want detecting the file system and processing them slightly differently, annoying and perhaps not stronly enough motivate to be worth the effort!
cheers for a handy plugin anyway, and for a fix that works for me (:

**Pull request closed without merging**
