### PR TITLE
Abstract keyword patterns

### PR DESCRIPTION
**Pull request by ErichDonGubler**
## Motivation

I am submitting this PR in light of discussion after my submission of [issue #109](https://github.com/jonathandelgado/SublimeTodoReview/issues/109).

In essence, I would like to use code to the left of my comment as the note for the todo. You are forced to use different patterns if you want to do this:

```c++
class Something //TODO: Make all members private!
//...
friend std::ostream& operator<<(std::ostream& os, const MyClass& mc); //TODO
```

The problem can only be approached with what I would call a hack. Python does not permit multiple definitions of a named capture group, so I'm forced to use a different name entirely for what is effectively the same thing (i.e., `(?P<todo_back>)`). In this PR, I have combined this with the separation of abstract overall patterns from keywords to make something I feel to be a better configuration design. It solves the problem, and frankly is more intuitive and therefore less prone to error.

## Thought

In thinking of how to design this fix, best way I imagined to resolve this would be change design. Consider the following config after adding my own custom keywords:

```json
{
	"patterns":
	{
		"TODO": "TODO[\\s]*:[\\s]*(?P<todo>.*)$",
		"TEST": "TEST[\\s]*:[\\s]*(?P<test>.*)$",
		"FIXME": "FIX ?ME[\\s]*:[\\s]*(?P<fixme>.*)$",
		"XXX": "XXX[\\s]*:[\\s]*(?P<xxx>.*)$",
		"DOCUMENT": "DOC(?:UMENT)?[\\s]*:[\\s]*(?P<document>.*)$",
		"DEBUG": "DEBUG[\\s]*:[\\s]*(?P<debug>.*)$",
		"REMOVE": "REMOVE[\\s]*:[\\s]*(?P<remove>.*)$"
	},
	"patterns_weight":
	{
		"FIXME": 4,
		"XXX": 6,
		"TODO": 7
	}
}
```

### Observations
 
* The patterns are repetitive. I find it very unlikely that users will want to vary much from the overall pattern with individual keywords *(please correct me if I'm wrong!)*. The pattern provided by vanilla config is basically of the form `(?P<keyword>\\w+)\\s*:\\s*(?P<note>.*)$`.
* I have different config sections for different properties of the same keyword (`patterns` and the weights in `patterns_weight`). Design principles guide us to separate what changes from what stays the same.

## Solution 

It seems to me that one could achieve a more cohesive result by associating attributes to individual keywords with a map, which are plugged into the abstract patterns.

I think a good design to handle this could be as follows:

1. Change `patterns` to a list of abstract patterns from current dictionary of keywords and their associated patterns. Use group names for different fields of the abstract pattern, the only two of which I can think of right now are `keyword` and `note`.
2. Recognize user definitions of todo categories with a `keywords` dictionary. Expect category names to map to their own configuration dictionaries, thus having a cohesive area for properties like `weight` and a custom `pattern` for the keyword.

Starting with something we recognize, the equivalent of the default configuration would be:

```json
{
	"patterns": [
		"(?P<keyword>\\w+)\\s*:\\s*(?P<note>.*)$"
	],
	"keywords": {
		"TODO": {}
	}
}
```

...where  the `TODO` category uses the pattern `"TODO"` and has a weight of 100 (both by default, the former according to the [current commit](https://github.com/jonathandelgado/SublimeTodoReview/commit/184988a453ed3fa9d2ef42d20b375004ed285231)).

Example configuration for weight and keyword pattern with new design:

```json
{
	"patterns":
	[
		"(?P<keyword>\\w+)\\s*:\\s*(?P<note>.*)$",
		"^\\s*(?P<note>.*)(\\/\\/|#)\\s*(?P<keyword>\\w+)\\s*$"
	],
	"keywords":
	{
		"FIXME":
		{
			"pattern": "FIX(?:ME)?",
			"weight": 4
		},
		"XXX":
		{
			"weight": 6
		},
		"TODO": {}
	}
}
```

The second line in the `patterns` list implements the motivation for this PR easily.

This would allow you do get this:

```
// domingo 04/05/15 at 06:35 - 1 files in 0.01 secs

## FIXME (1)
1. Desktop/asdf.d:3   void broken(){}

## TODO (1)
1. Desktop/asdf.d:7   Say something flashy!

```

...from example source file `asdf.d`:

```d
import std.stdio;

void broken(){}//FIXME

int main(string[] args)
{
	writeln("Hello, world!");//TODO: Say something flashy!
	return 0;
}
```

### Other Consequences

* Defining keyword-specific patterns is actually facilitated by this design also -- there's less copypasta than before. If you wanted to restrict my desired todo solution only to the keywords TODO and DOCUMENT, you'd do something like this:

```json
{
	"patterns":
	[
		"(?P<keyword>\\w+)\\s*:\\s*(?P<note>.*)$",
		"^\\s*(?P<note>.*)(\\/\\/|#)\\s*(?P<keyword>TODO|DOC(?:UMENT)?)\\s*$"
	],
	"keywords":
	{
		"FIXME":
		{
			"pattern": "FIX(?:ME)?",
			"weight": 4
		},
		"XXX":
		{
			"weight": 6
		},
		"TODO": {},
		"DOCUMENT":
		{
			"pattern": "DOC(?:UMENT)?",
			"weight": 1
		}
	}
}
```
* Abstract design for overall todo patterns will immensely facilitate adding other fields to the TodoReview tab (like an explicit `(?P<code>)` field, or something).

### CODE REVIEW

**Comment by jonathandelgado** [comment]
It's a little hard to say "no" to a PR this detailed, but I have some major problems with this.

Firstly, I don't want to break current user configs. If I were to push this today, all current users would have a broken patterns object. The entire plugin would seemingly stop working, which is unacceptable in my opinion. I would really prefer the pattern and weight settings be left alone, i'm perfectly fine with adding new keys to the config though.

Also, you completely broke, I would even say removed, the priority system. I'm not sure if you got the weight and priority properties confused; weight is the overall pattern sort, while priority is a number match within each result. The priority system needs to be reverted completely.

Though I think the concept of keywords would be an interesting addition, I think your implementation needs tweaking. I don't think users want to match literally anything, i'll give you an example. If I have the following code:

```
param.test(/match/);
```

Using your keyword system, matching "test," which is a very common pattern for this plugin, it would match this line. For this to work, you have to regex match the end of the line, so we know it is meant as a comment and not inline code. With that being said, it should also be smart enough to grab the corresponding todo message if there is one. I'm not sure exactly how that could work.

Additionally, the keyword regex's  should really be combined prior to searching and only executed once per line. This PR significantly increased the time it took to search through ~2k files from 2sec to around 10sec, but that can be easily fixed.

If you do fix what I mentioned, please also remove the comments within the code and remove yourself from the author header. The author header is only meant to satisfy the MIT requirement of crediting original sources, since this repo is essentially a fork of a previous plugin, it's not for tracking contributors.

I don't want to sound discouraging, I think you are headed in a good direction with the concept of keywords, but i'm sure you can understand I want the code to be well written because i'm going to be the one maintaining it.

**Comment by ErichDonGubler** [comment]
I'm going to respond in chunks here.

> Though I think the concept of keywords would be an interesting addition, I think your implementation needs tweaking. I don't think users want to match literally anything, i'll give you an example. If I have the following code:

>     param.test(/match/);

> Using your keyword system, matching "test," which is a very common pattern for this plugin, it would match this line. For this to work, you have to regex match the end of the line, so we know it is meant as a comment and not inline code. With that being said, it should also be smart enough to grab the corresponding todo message if there is one. I'm not sure exactly how that could work.

My first response is...did you test against this particular example?

The point of defining `keywords` is to filter through the contents of the `keyword` regex group in the abstract patterns provided. Using an example `TodoReview.sublime-settings`, this will ONLY recognize the defined keywords `TEST`, `TESTING`, `DEBUG`, `REMOVE`, `FIX`, `FIXME`, `DOCUMENT`, `XXX`, and `TODO`:

```json
{
	"patterns":
	[
		"(?P<keyword>\\w+)\\s*:\\s*(?P<note>.*)$",
		"^\\s*(?P<note>.*)(\\/\\/|\\#)\\s*(?P<keyword>\\w+)\\s*$"
	],
	"keywords":
	{
		"TEST":
		{
			"pattern": "TEST(?:ING)?",
			"weight": 1
		},
		"DEBUG": { "weight": 2 },
		"REMOVE": { "weight": 3 },
		"FIXME":
		{
			"pattern": "FIX(?:ME)?",
			"weight": 4
		},
		"DOCUMENT":
		{
			"weight": 5
		},
		"XXX": { "weight": 6 },
		"TODO": {}
	}
}
```

I don't see how this PR changes the responsibility the end user has to assure this doesn't happen. It's matching exactly what you tell it to -- it would depend upon the user to provide the correct abstract keyword regex. That said, the default regex I provided DOES look for the end of the line. I tried to make it behave exactly like the default string you provided from before. I ran this test without matching what you wrote:

* `TodoReview.sublime-settings` from example above

* `asdf.txt`:
```txt
param.test(/match/);
param.test(/match/); // TEST
param.test(/match/); // TEST: asdf
param.test(/match/); // DEBUG
param.test(/match/); // DEBUG: asdf
param.test(/match/); // DOCUMENT
param.test(/match/); // DOCUMENT: asdf
param.test(/match/); // REMOVE
param.test(/match/); // REMOVE: asdf
param.test(/match/); // FIXME
param.test(/match/); // FIXME: asdf
param.test(/match/); // FIX
param.test(/match/); // FIX: asdf
param.test(/match/); // DOCUMENT
param.test(/match/); // DOCUMENT: asdf
param.test(/match/); // XXX
param.test(/match/); // XXX: asdf
param.test(/match/); // TODO
param.test(/match/); // TODO: asdf
```

* `TodoReview` tab:
```cpp
// segunda 04/06/15 at 11:17 - 1 files in 0.01 secs

## DEBUG (2)
1. Desktop/asdf.txt:4    param.test(/match/); 
2. Desktop/asdf.txt:5    asdf

## DOCUMENT (4)
1. Desktop/asdf.txt:6    param.test(/match/); 
2. Desktop/asdf.txt:7    asdf
3. Desktop/asdf.txt:14   param.test(/match/); 
4. Desktop/asdf.txt:15   asdf

## FIXME (4)
1. Desktop/asdf.txt:10   param.test(/match/); 
2. Desktop/asdf.txt:11   asdf
3. Desktop/asdf.txt:12   param.test(/match/); 
4. Desktop/asdf.txt:13   asdf

## REMOVE (2)
1. Desktop/asdf.txt:8    param.test(/match/); 
2. Desktop/asdf.txt:9    asdf

## TEST (2)
1. Desktop/asdf.txt:2    param.test(/match/); 
2. Desktop/asdf.txt:3    asdf

## TODO (2)
1. Desktop/asdf.txt:18   param.test(/match/); 
2. Desktop/asdf.txt:19   asdf

## XXX (2)
1. Desktop/asdf.txt:16   param.test(/match/); 
2. Desktop/asdf.txt:17   asdf

```

Concluding, I'm not sure if your concern is valid.

**Comment by ErichDonGubler** [comment]
> Firstly, I don't want to break current user configs. If I were to push this today, all current users would have a broken patterns object. The entire plugin would seemingly stop working, which is unacceptable in my opinion. I would really prefer the pattern and weight settings be left alone, i'm perfectly fine with adding new keys to the config though.

I think your point is very important. I understand your concerns with wanting to maintain your design, but I can't think of a good way to implement a solution to the issue I presented using it. Remember that the requirements I thought of for my problem were to have a wholly different pattern for the same keyword, which doesn't play nice with current design. 

You can always communicate to users beforehand to ease breaks, though. Do you think the transition would be difficult? I'm more than willing to document a deprecation/transition path, if that's what you're worried about.

**Comment by ErichDonGubler** [comment]
> Additionally, the keyword regex's should really be combined prior to searching and only executed once per line. This PR significantly increased the time it took to search through ~2k files from 2sec to around 10sec, but that can be easily fixed.

You're right. I'm still thinking how to resolve this. Merging `keywords` regexes would be a good optimization, but I don't see how to get around comparing multiple `patterns` regexes because they rely on having the same group names. So the design I presented might have to adapt for that.

**Comment by ErichDonGubler** [comment]
> Also, you completely broke, I would even say removed, the priority system. I'm not sure if you got the weight and priority properties confused; weight is the overall pattern sort, while priority is a number match within each result. The priority system needs to be reverted completely.

Gah! That's my bad right there. Sorry about that! I'll fix it.

**Comment by jonathandelgado** [comment]
@ErichDonGubler Alright, I figured out why I was matching `param.test(/match/);`, I was running on a previous config with a different pattern set. When I initially reviewed this PR, I didn't realize that you completely removed the pattern system as well, it looked initially like (to me) you merged the array of patterns with the array of keywords.

With that being said, there are a lot of changes here to the engine to fix one thing, like I mentioned I didn't want to happen in #109.

Points that must be fixed:
- **Pattern system must be retained.** A lot of users use odd regexs to match non-traditional todo comments, myself included.
- **Users config must not be broken.** I don't think the feature added here warrants making all users change their configs, consider using different setting key names.
- **The priority system must be fixed.** As you noted, it was removed by accident.
- **The speed must be comparable to what it is currently.** The speed that it is at right now is unacceptable, as you noted.
- **Misc code formatting I mentioned.** Just removing the MIT author and code comments.

I think ultimately, the only was this is going to be achieved, realistically, is rewriting the engine as I noted in #109, which I really don't want to do.

**Comment by jonathandelgado** [comment]
Going to close as stale, let me know if you have any additional thoughts on this.

**Pull request closed without merging**
