### PR TITLE
Feature/open file with mouse

### PR DESCRIPTION
**Pull request by Rylon**
Hey there,

I added mouse mappings to allow a user to open a file in the todo list by double-clicking on it. Would you please consider merging this feature?

Thanks!
Ryan

### CODE REVIEW

**Comment by toddpi314** [comment]
Confirming that the enter command will drive to the file. But, this is kind of a bottleneck when you have thousands of results.

Thanks for the hard work guys.

**Comment by jonathandelgado** [comment]
@FichteFoll had some ideas here: https://github.com/jonathandelgado/SublimeTodoReview/issues/136#issuecomment-161844620

**Comment by lone-lion** [comment]
Salut! This package manages that well: **PlainTasks**.

Check the image in the description (under the title "_File links_"), here: [https://github.com/aziz/PlainTasks](https://github.com/aziz/PlainTasks).
Or install it, then check _Preferences >Package Settings >PlainTasks >**Tutorial**_

**Overview:**
> File links:
>    ☐ **You can create a link to a file** by prefixing the file name with a dot and (back)slash sign
>      like: .\filename\ or ./another filename/
>      It supports only one filename per line
>      Filename can be absolute path or relative one (to project folder(s) or to open files)
>    **☐ The line and column numbers can be specified by colons after the filename: .\filename:11:8**
>    ☐ In SublimeText 3 you can specify a symbol inside the file by using > character like: .\filename>symbol
>    ☐ In SublimeText 2 you can specify a text inside that file by using double quotes like: .\filename"any text"
>    **☐ ctrl+o (alt+o on Windows) opens the file in Sublime: try to open .\install.txt\**
>    ☐ In SublimeText 3 link may point to directory, open such link will add the directory to current project (sidebar), e.g. .\..\PlainTasks\
>    **☐ Other ways to create file links:**
>       \[](install.txt)  ← try to open it
>       **\[](path ":11:8")
>       \[](path ">symbol")
>       \[](path "any text")**
>       [[..\PlainTasks.py]]  ← try to open it
>       [[path::11:8]]
>       [[path::*symbol]]
>       [[path::any text]]
>       [[path]] ":11:8"
>       [[path]] ">symbol"
>       [[path]] "any text"

ll.

**Comment by byaka** [comment]
really needed feature, any progress on it?

**Comment by FichteFoll** [comment]
Not from my side, unfortunately.

**Comment by Kristinita** [comment]
@jonathandelgado , please, accept or decline this pull request. I think, open pull request, opened a few years ago — is a bad practice.

Thanks.

**Comment by tablatronix** [comment]
I wonder , Has this changed since? I know some modal and html support was added to views. I agree this is alot of unjustifiable work unless new mechanisms were introduced to ST3 to make implementation better

**Comment by FichteFoll** [comment]
With the new APIs this is definitely possible and a lot easier too. It just hasn't been looked into yet. I still intend to use this packcage and fix a couple hiccups when I encounter, including mouse navigation, but it hasn't happened yet and at this point I can't say when it will.

**Comment by Rylon** [comment]
Closing this as it's years out of date now and looks like it was added in #170 :)

**Comment by FichteFoll** [comment]
#170 actually referenced this issue as it was used to keep track of this request, but I agree there should be a new issue for this since this PR isn't going to be merged.

**Comment by FichteFoll** [comment]
For the time being, I've been using https://github.com/SublimeLinter/SublimeLinter-annotations/ with the SublimeLinter panel with huge success since SL4 was released. It only covers open tabs and not the entire project, but it updates in realtime and has good navigation options (including double-clicking with the mouse).

**Pull request closed without merging**
